### ISSUE TITLE
(Suggestion) Track "boss died X mins ago"

### ISSUE THREAD

**Issue by Nillx** [melroy999/RareTrackerWorldBosses#1]
Hello, currently there is a way to see when the boss died. Im using an addon called NPC Time - https://www.curseforge.com/wow/addons/npctime which is displaying when the boss died.
![Screenshot 2022-06-15 152806](https://user-images.githubusercontent.com/34476875/173827200-747da7cc-de78-4b6d-b274-c66d3725ad18.jpg)

Its quite useful on Sha of Anger because the corpse stays on the ground until the boss starts spawning again (sometimes its despawning earlier, i dont know why). I guess you can change the X boss last seen to get updated from that info? 

Also im currently using a weak aura that requires me to target the dead boss , then plays a loud horn sound when the corpse despawn and counts from 30 to 0. (smoke spawn event lasts for 30 seconds) Then the boss spawns.

**Comment by melroy999** [comment]
Curious, I wasn't aware that the spawn time of an entity can be found within its GUID. I have to agree that using the given time offset makes sense for world bosses, given their tendency to die shortly after spawning--I will take a look at the technique used and see if it can be added to the RTC module to get more accurate timers for both world bosses and rares.

However, I am conflicted on adding a countdown timer, since it is functionality that is generally only useful for world bosses of which the respawn timer is known exactly, while my addon is at its core designed for rare tracking which doesn't have clear respawn timers. As such, I consider the use of a weak aura to be the better option, given that it is created solely for that purpose.

**Comment by Nillx** [comment]
Yeah i agree with the spawn timer, its not always accurate because the boss tends to despawn randomly sometimes on some realms.

**Comment by Nillx** [comment]
Thanks for the update, works great like this.

**Comment by Nillx** [comment]
Got 2 more suggestions. 

- Now since you know the exact time when the boss died, i can see you change the General chat msg that says "Sha of anger was last seen ~X mins ago" to something more accurate like " Sha of anger was killed XXmin:XXsec ago"

- Is it possible to change the count timer to be a bit more accurate? ![Screenshot 2022-06-16 144040](https://user-images.githubusercontent.com/34476875/174062622-166f8182-1e50-4a12-9eef-43a95bf14f7c.jpg) Think its better to show the seconds as well. Ive seen Sha respawn exactly at the 20m00sec timer a few times and with with that info you can stand there and prepare for the spawn. Galleon is at a fixed respawn timer so i can see that being useful there too.

**Comment by melroy999** [comment]
The time given in the general chat message and overview is purposefully vague due to two reasons: 

- first, it cannot be guaranteed that the given numbers are accurate to the second, especially now that the kill time may be based upon the spawn time instead. As such, a little variance is likely to occur depending on how quickly the world boss is killed, so even if the spawn timer is known, the number given by the addon is likely to be a value a few seconds or more over that. 
- Secondly, it is currently difficult to apply settings to just one of the modules—it does make sense when having just one entity tracked, but as you may imagine, it can be quite distracting to see the counter of 20+ rares change every second.

Therefore, I suggest the following: an option will be added that shows the rare timers in the format “mins:secs,” but it won’t be the default setting. Would this be acceptable?

**Comment by Nillx** [comment]
Fair enough, an option to change is always better!
